version: "2"

services:
  postgres:
    restart: always
    image: postgres:10.0
    env_file: ./etc/envs/postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./volumes/postgres_initial:/docker-entrypoint-initdb.d

  rabbit:
    restart: always
    image: rabbitmq:alpine
    env_file: ./etc/envs/rabbitmq

  elasticsearch-dev:
    restart: always
    image: elasticsearch:5.6.3
    env_file: "./etc/envs/elasticsearch-dev"
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

  elasticsearch:
    restart: always
    image: elasticsearch:5.6.3
    env_file: "./etc/envs/elasticsearch-prod"
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data