# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20170515_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstat',
            name='agent',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='userstat',
            name='referer',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
