# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20170617_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u043d \u0438\u043b\u0438 \u043e\u0442\u0432\u0435\u0447\u0435\u043d'),
        ),
    ]
