# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_auto_20170625_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstat',
            name='article',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
