# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_userstat_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstat',
            name='article',
        ),
    ]
