# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='answer_count',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043e\u0442\u0432\u0435\u0442\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='poll_count',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433'),
        ),
    ]
