# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_auto_20170505_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='end_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 24, 15, 32, 35, 95205, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
