# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0004_mainuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='user_has_password',
            field=models.BooleanField(default=True),
        ),
    ]
