# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0006_auto_20170606_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authe.City'),
        ),
    ]
