# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0007_mainuser_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='user_has_password',
        ),
    ]
