# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0008_remove_mainuser_user_has_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
