# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0009_mainuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default=b'KZ', max_length=100, verbose_name='\u041a\u043e\u0434'),
        ),
    ]
