# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0012_auto_20170703_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetEmailRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.CharField(blank=True, max_length=50, verbose_name='New Email')),
                ('key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
