# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0013_resetemailrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d'),
        ),
    ]
