# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0017_auto_20170815_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='user_type',
            field=models.SmallIntegerField(choices=[(0, 'email register'), (1, 'telephone register'), (2, 'facebook register'), (3, 'undefined')], db_index=True, default=0, verbose_name='\u0422\u0438\u043f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f'),
        ),
    ]
