# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0018_mainuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='avatar_height',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='avatar_width',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
