# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 07:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0020_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='follower_user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='following_user_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u0434\u043f\u0438\u0441\u043e\u043a'),
        ),
    ]
