# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0022_blacklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('name', 'country')]),
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together=set([('name', 'code')]),
        ),
    ]
