# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 13:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0022_blacklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushTokenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('push_token', models.CharField(blank=True, max_length=500, null=True)),
                ('push_os', models.SmallIntegerField(choices=[(0, 'WEB'), (1, 'IOS'), (2, 'ANDROID')], default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '\u0422\u043e\u043a\u0435\u043d \u043f\u0443\u0448-\u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0422\u043e\u043a\u0435\u043d\u044b \u043f\u0443\u0448-\u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.AddField(
            model_name='mainuser',
            name='category_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u043a\u0430\u0442\u0433\u043e\u0440\u0438\u0439'),
        ),
        migrations.AddField(
            model_name='pushtokenlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
