# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 07:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0024_remove_pushtokenlog_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='category_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='\u0421\u043f\u0438\u0441\u043e\u043a \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439'),
        ),
    ]
