# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0025_auto_20170914_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='push',
            field=models.BooleanField(default=True, verbose_name='\u041e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 push \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0439'),
        ),
    ]
