# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0027_auto_20170915_1024'),
        ('authe', '0023_auto_20170920_1325'),
    ]

    operations = [
    ]
