# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0029_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='mainuser',
            name='notification_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043d\u0435\u043f\u0440-\u0445 \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0439'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='answer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043e\u0442\u0432\u0435\u0442\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='poll_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='repost_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u0440\u0435\u043f\u043e\u0441\u0442\u043e\u0432'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
