# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0030_auto_20170927_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435')),
                ('payload', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('push_type', models.SmallIntegerField(choices=[(0, 'Dummy push'), (1, '\u041e\u043f\u0440\u043e\u0441 \u0441\u043e\u0437\u0434\u0430\u043d'), (2, '\u041e\u043f\u0440\u043e\u0441 \u043e\u0442\u0432\u0435\u0447\u0435\u043d'), (3, '\u041e\u043f\u0440\u043e\u0441 \u0437\u0430\u043a\u043e\u043d\u0447\u0435\u043d')], default=0, verbose_name='\u0422\u0438\u043f \u0443\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u0423\u0432\u0435\u0434\u043e\u043c\u043b\u0435\u043d\u0438\u044f',
            },
        ),
    ]
