# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0031_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_verion', models.CharField(max_length=100, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f iOS')),
                ('and_verion', models.CharField(max_length=100, verbose_name='\u0412\u0435\u0440\u0441\u0438\u044f And')),
            ],
            options={
                'verbose_name': '\u0412\u0435\u0440\u0441\u0438\u044f \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0412\u0435\u0440\u0441\u0438\u0438 \u043f\u0440\u0438\u043b\u043e\u0436\u0435\u043d\u0438\u0439',
            },
        ),
    ]
