# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0032_appversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pushtokenlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='notification_count',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PushTokenLog',
        ),
    ]
