# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0033_auto_20171005_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='following',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='follower_user_ids',
        ),
        migrations.RemoveField(
            model_name='mainuser',
            name='following_user_ids',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
