# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0034_auto_20171005_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='push',
        ),
    ]
