# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0035_remove_mainuser_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='push_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
