# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0036_mainuser_push_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='partner_author',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u041f\u0430\u0440\u0442\u043d\u0435\u0440 / \u0430\u0432\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='partner_details',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='profile_type',
            field=models.PositiveIntegerField(default=0, verbose_name='\u0422\u0438\u043f \u043f\u0440\u043e\u0444\u0438\u043b\u044f'),
        ),
    ]
