# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0038_mainuser_partner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='partner_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
    ]
