# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0039_mainuser_partner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='showable_votem',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437 \u0432\u0441\u0435\u0445 \u0433\u043e\u043b\u043e\u0441\u043e\u0432'),
        ),
    ]
