# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollkeyword',
            name='keyword',
        ),
        migrations.AddField(
            model_name='pollkeyword',
            name='poll_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Keyword', verbose_name='\u0422\u0435\u0433'),
        ),
    ]
