# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170504_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polltopic',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='polltopic',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'},
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='topic',
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PollTopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
