# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170504_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_begin',
            field=models.BigIntegerField(default=0, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u043e\u043f\u0440\u043e\u0441\u043d\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.BigIntegerField(default=0, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043e\u043f\u0440\u043e\u0441\u043d\u0438\u043a\u0430'),
        ),
    ]
