# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170512_1523'),
        ('polls', '0007_auto_20170513_1234'),
    ]

    operations = [
    ]
