# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20170530_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCategories',
            new_name='UserCategory',
        ),
    ]
