# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 10:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_poll_facebook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='category_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterUniqueTogether(
            name='pollcategory',
            unique_together=set([('poll', 'category')]),
        ),
    ]
