# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 13:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_merge_20170515_1619'),
        ('polls', '0013_auto_20170610_1011'),
    ]

    operations = [
    ]
