# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_usercategory_count'),
        ('polls', '0014_merge_20170617_1303'),
    ]

    operations = [
    ]
