# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 13:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_create_gin_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='poll',
            name='polls_poll_title_s_ca66b1_gin',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='title_sv',
        ),
        migrations.AlterField(
            model_name='poll',
            name='category_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, default=[], size=None, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='date_begin',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u043e\u043f\u0440\u043e\u0441\u043d\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='keywords_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), db_index=True, default=[], size=None, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.SmallIntegerField(choices=[(0, 'rating scale'), (1, 'single choice'), (2, 'multiple choice')], db_index=True, default=1, verbose_name='\u0422\u0438\u043f \u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
