# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20170713_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date_end',
            field=models.BigIntegerField(db_index=True, default=0, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u043e\u043f\u0440\u043e\u0441\u043d\u0438\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, height_field=b'height', null=True, upload_to=b'poll_avatars', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
