# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20170724_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='height_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='width_value',
            field=models.IntegerField(default=0),
        ),
    ]
