# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20170724_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='height_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='width_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
