# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20170724_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='height_value',
            new_name='fb_image_height',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='width_value',
            new_name='fb_image_width',
        ),
        migrations.AddField(
            model_name='poll',
            name='image_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='image_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
