# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-24 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20170724_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='facebook_image',
            field=models.ImageField(blank=True, height_field=b'fb_image_height', null=True, upload_to=b'poll_facebook_avatars', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043e\u043f\u0440\u043e\u0441\u0430 \u0434\u043b\u044f facebook', width_field=b'fb_image_width'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, height_field=b'image_height', null=True, upload_to=b'poll_avatars', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043e\u043f\u0440\u043e\u0441\u0430', width_field=b'image_width'),
        ),
    ]
