# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20170724_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'approved'), (1, 'unknown'), (0, 'rejected')], db_index=True, default=1, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441 \u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
