# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-08 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_keyword_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='rank',
            field=models.FloatField(default=0, verbose_name='\u041f\u043e\u043f\u0443\u043b\u044f\u0440\u043d\u043e\u0441\u0442\u044c \u043e\u043f\u0440\u043e\u0441\u0430'),
        ),
    ]
