# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20170814_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollanswer',
            name='user_cookie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u0421\u0433\u0435\u043d\u0435\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u044b\u0439 \u043a\u0443\u043a\u0438'),
        ),
    ]
