# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 10:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_auto_20170824_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='choices_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), db_index=True, default=[], size=None, verbose_name='\u041e\u0442\u0432\u0435\u0442\u044b'),
        ),
    ]
