# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_poll_choices_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='sc_value',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435 single_choice \u043e\u0442\u0432\u0435\u0442\u0430'),
        ),
    ]
