# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_auto_20170926_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='private_code',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='\u041f\u0440\u0438\u0432\u0430\u0442\u043d\u044b\u0439 \u043a\u043b\u044e\u0447'),
        ),
    ]
