# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_poll_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='privacy_type',
        ),
    ]
