# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_remove_poll_privacy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa3\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xb0'),
        ),
    ]
