# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_poll_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='partner_url',
            field=models.CharField(default=b'', max_length=250, verbose_name='url \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430'),
        ),
    ]
