# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_poll_partner_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='slug',
            field=models.SlugField(default='', max_length=150, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
            preserve_default=False,
        ),
    ]
