# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_poll_partner_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0432\u0438\u0434\u0435\u043e'),
        ),
    ]
