# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_poll_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='slug',
            field=models.SlugField(max_length=1000, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430'),
        ),
    ]
