# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_poll_video'),
        ('polls', '0047_auto_20171218_0804'),
    ]

    operations = [
    ]
