# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_pollcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollcomment',
            options={'ordering': ['timestamp'], 'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043e\u043f\u0440\u043e\u0441\u0430', 'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u043e\u043f\u0440\u043e\u0441\u043e\u0432'},
        ),
        migrations.AddField(
            model_name='pollcomment',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u041f\u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 \u0433\u0430\u043b\u043e\u0447\u043a\u0443, \u0447\u0442\u043e\u0431\u044b \u043e\u0442\u043e\u0431\u0440\u0430\u0437\u0438\u0442\u044c \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043d\u0430 \u0441\u0430\u0439\u0442\u0435'),
        ),
    ]
