# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_auto_20180106_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='comment_status',
            field=models.BooleanField(default=False, verbose_name='\u0420\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u043d\u0430 \u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
