# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_poll_comment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollcomment',
            options={'ordering': ['-timestamp'], 'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439 \u043e\u043f\u0440\u043e\u0441\u0430', 'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438 \u043e\u043f\u0440\u043e\u0441\u043e\u0432'},
        ),
        migrations.AddField(
            model_name='poll',
            name='private_survey',
            field=models.BooleanField(default=False, verbose_name='\u041f\u0440\u0438\u0432\u0430\u0442\u043d\u044b\u0439 \u043e\u043f\u0440\u043e\u0441'),
        ),
    ]
