# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollChoiceTemplate',
            fields=[
                ('pollchoice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.PollChoice')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u043e\u0442\u0432\u0435\u0442\u0430 \u043e\u043f\u0440\u043e\u0441\u043e\u0432',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u043e\u0442\u0432\u0435\u0442\u043e\u0432 \u043e\u043f\u0440\u043e\u0441\u043e\u0432',
            },
            bases=('polls.pollchoice',),
        ),
        migrations.CreateModel(
            name='PollTemplate',
            fields=[
                ('poll_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polls.Poll')),
            ],
            options={
                'verbose_name': '\u0428\u0430\u0431\u043b\u043e\u043d \u043e\u043f\u0440\u043e\u0441\u043e\u0432',
                'verbose_name_plural': '\u0428\u0430\u0431\u043b\u043e\u043d\u044b \u043e\u043f\u0440\u043e\u0441\u0430',
            },
            bases=('polls.poll',),
        ),
    ]
