# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170512_1523'),
        ('moderators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollTemplateCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_polls', to='polls.Category')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_categories', to='moderators.PollTemplate')),
            ],
            options={
                'verbose_name': '\u041a\u043b\u044e\u0447\u0435\u0432\u0430\u044f \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f \u0448\u0430\u0431\u043b\u043e\u043d\u0430',
                'verbose_name_plural': '\u041a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438 \u0448\u0430\u0431\u043b\u043e\u043d\u043e\u0432',
            },
        ),
    ]
