# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_merge_20170628_1547'),
        ('moderators', '0002_polltemplatecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.CharField(max_length=1000, verbose_name='URL \u0441\u0442\u0430\u0442\u044c\u0438')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438',
            },
        ),
        migrations.CreateModel(
            name='ArticlePollEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderators.Article')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
            options={
                'verbose_name': '\u041e\u043f\u0440\u043e\u0441 \u0441\u0442\u0430\u0442\u044c\u0438',
                'verbose_name_plural': '\u041e\u043f\u0440\u043e\u0441\u044b \u0441\u0442\u0430\u0442\u044c\u0438',
            },
        ),
    ]
