# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 15:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0003_article_articlepollentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': '\u0421\u0442\u0430\u0442\u044c\u044f', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u044c\u0438'},
        ),
        migrations.AddField(
            model_name='article',
            name='poll_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None, verbose_name='ID \u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.CharField(max_length=1000, unique=True, verbose_name='URL \u0441\u0442\u0430\u0442\u044c\u0438'),
        ),
        migrations.AlterField(
            model_name='articlepollentry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_entry', to='moderators.Article'),
        ),
    ]
