# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 15:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0004_auto_20170703_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='poll_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None, verbose_name='ID \u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
    ]
