# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0005_auto_20170703_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepollentry',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_entry_set', to='moderators.Article'),
        ),
    ]
