# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0006_auto_20170711_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430'),
        ),
    ]
