# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 08:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0008_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=[], size=None, verbose_name='\u0422\u0435\u0433\u0438 \u043e\u043f\u0440\u043e\u0441\u043e\u0432'),
        ),
    ]
