# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderators', '0010_auto_20170816_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepollentry',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_set', to='polls.Poll'),
        ),
    ]
